### PR TITLE
CENO import Ouinet from repo (ceno-browser)

### PR DESCRIPTION
**Pull request by mhqz**
Hi @ivilata, I hope you're doing great :) 

In this branch I'm adding a new option to the build scripts that serves to indicate if Ouinet is going to be built locally or directly fetched from MavenCentral (when the option `-o`  is missing).

```bash
# The default behavior is to fetch the latest version of Ouinet [1] from MavenCentral.
 ./build.sh -a x86_64 -x ouinet.sample.xml

# If the -o option is present Ouinet is built from sources and passed as a parameter to build-fennec.sh
 ./build.sh -a x86_64 -x ouinet.sample.xml -o
```
**[1]** The latest version of Ouinet is [automatically defined](https://github.com/censorship-no/gecko-dev/pull/1/files#diff-b32e9c9736efe96d6fb19cba5145eac8899326f11b9d85edbc036f2ca1474c07R240) by reading the `version.txt` file included in Ouinet's subrepo:

```groovy
def ouinet_latest_version = file('../../../../ouinet/version.txt').text.trim()
implementation "ie.equalit.ouinet:ouinet-${System.env.OUINET_ABI}:${ouinet_latest_version}"
```

BTW, I've also opened a [PR in gecko-dev repo](https://github.com/censorship-no/gecko-dev/pull/1) to upgrade the related Gradle build scripts.

Please let me know if you have any questions or comments :smile_cat:

### CODE REVIEW

**Comment by ivilata** [comment]
Thanks @mhqz! A couple of things:

1. It would be nice to have the new option documented in the readme, since it contains instructions for both debug and release builds.
2. As mentioned in [gecko-dev#1](https://github.com/censorship-no/gecko-dev/pull/1), it should be `ceno-browser` scripts which decide what version of Ouinet to use for building `gecko-dev`. So, if `-o` is not specified, do read Ouinet's version from `ouinet/version.txt` (e.g. in `build-fennec.sh`) and pass it on to the `gecko-dev` build process (e.g. via `OUINET_VERSION` as suggested there).

**Comment by mhqz** [comment]
Hi @ivilata, thanks a lot for your feedback :slightly_smiling_face: 

>     1. It would be nice to have the new option documented in the readme, since it contains instructions for both debug and release builds.
> 

I've added the instructions for option `-o` and `OUINET_VERSION` in 7244a33. I've also updated the supported ABIs when a release is built in 18f20ca.

>     2. As mentioned in [gecko-dev#1](https://github.com/censorship-no/gecko-dev/pull/1), it should be `ceno-browser` scripts which decide what version of Ouinet to use for building `gecko-dev`. So, if `-o` is not specified, do read Ouinet's version from `ouinet/version.txt` (e.g. in `build-fennec.sh`) and pass it on to the `gecko-dev` build process (e.g. via `OUINET_VERSION` as suggested there).

You're totally right about this point, so I've modified the build scripts to pass `OUINET_VERSION` when `build-fennec.sh` is invoked and got a default version if this value is not present (017ed81).

I've also tested the build scripts with all the supported ABIs and combining flags (to build locally or to import a different version of Ouinet from MavenCentral).

Please let me know if you have any questions or comments.

**Comment by ivilata** [comment]
All correct, thanks @mhqz! :smile:

**Comment by ivilata** [comment]
I fixed the build command for GitLab CI/CD in commit 106dde56, since it should use the Ouinet submodule and not the latest stable release.

**Pull request merged**
